ROOT=..\..
LOCAL_CXXFLAGS=-I${ROOT}/import/mingw/include -I../
LOCAL_LDFLAGS=-L${ROOT}/import/mingw/lib -L${ROOT}/lib -lmingw32 -lmutiny -lSDLmain -lSDL -lSDL_image -lGLEW32 -lOpenGL32 -lGLU32
LOCAL_BIN=${ROOT}\bin\collision.exe

include ${ROOT}\tmpl\tmpl.mingw.Mk
