all:
	@cd mutiny && $(MAKE) -f Makefile.freebsd
	@cd tools/buccaneer && $(MAKE) -f Makefile.freebsd
	@cd experiment && $(MAKE) -f Makefile.freebsd
	@cd collision && $(MAKE) -f Makefile.freebsd

clean:
	@cd collision && $(MAKE) -f Makefile.freebsd clean
	@cd experiment && $(MAKE) -f Makefile.freebsd clean
	@cd tools/buccaneer && $(MAKE) -f Makefile.freebsd clean
	@cd mutiny && $(MAKE) -f Makefile.freebsd clean
